version: '3'

services:
  web:
    container_name: web
    restart: always
    build: ./images/django-gunicorn-base
    environment:
      GUNICORN_RELOAD: "true"
      GUNICORN_LOGLEVEL: "warning"
    volumes:
      - "static:/var/www/static"
      - "media:/var/www/media"
      - "./django_docker:/code"

  nginx:
    container_name: nginx
    restart: always
    build: ./images/nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - "static:/var/www/static"
      - "media:/var/www/media"
volumes:
  static:
  media:
